# Cálculo de Soluções para células criticas
### 31/01/2020
## INPUTs:
* Coordenadas das células críticas
* Azimutes das células críticas
* Distâncias máxima, configurável por células
* É esperado que a Planilha com células críticas tenha as colunas com estes nomes: \['ENodeB','Célula','azimute','DISTÂNCIA','LAT','LONG'\]
* DISTÂNCIA é a distancia máxima para procurar.

## OUTPUTs:
Uma nova planilha com as colunas  \['ENodeB','Célula','azimute','DISTÂNCIA','LAT','LONG'\] Além de \[Site_Solucao, Distância, Azimute\]

In [1]:
import pandas as pd
import numpy as np
import datetime
from geographiclib.geodesic import Geodesic
import math
geod = Geodesic.WGS84
import time

teste

# df_cel_Criticas 
## é a planilha com as células que queremos solução

#df_solucoes1 a 3 - São as planilhas com as soluções. Vamos rodar uma por uma.

In [134]:
#df_cel_Criticas = pd.read_excel('./TOYSET.xlsx', header=0, sheet_name=0)
#df_aba1 = pd.read_excel('./TOYSET.xlsx', header=0, sheet_name=1)
df_cel_Criticas = pd.read_excel('./toyset2.xlsx', header=0, sheet_name=0)

#df_spazio = pd.read_excel('./dados/Spazio_2020_03_16.xlsx', header = 0)
df_spazio = pd.read_csv('./dados/Spazio_2020_03_16.csv',sep=';', error_bad_lines=False)
df_solucoes5 = pd.read_excel('./toyset2.xlsx', header=0, sheet_name=1)
df_NT4G = pd.read_excel('./toyset2.xlsx', header=0, sheet_name=2)
#df_solucoes = df_solucoes1

In [135]:
df_NT4G.head()
#df_solucoes5.head()

        EndId    ENodeB     Célula Município Estado  Banda  AZIMUTE
0  RNCIC_0002  NLKCKC00  NLKCKC00F     Caico     RN    700      120
1  RNCIC_0002  NLKCKC00  NLKCKC00R     Caico     RN   2100      120
2  RNCIC_0002  NLKCKC00  NLKCKC00S     Caico     RN   2100      290
3  RNCIC_0002  NLKCKC00  NLKCKC00Q     Caico     RN   2100        0
4  RNCIC_0002  NLKCKC00  NLKCKC00G     Caico     RN    700      290

In [136]:
df_spazio = df_spazio[['Endereço ID','Latitude','Longitude']]
df_spazio.rename(columns={"Latitude": "LATITUDE", "Longitude": "LONGITUDE"}, inplace = True)

def converter(valor):
    resultado = valor.strip().replace(',','.')
    return resultado

df_spazio['LATITUDE'] = df_spazio['LATITUDE'].astype(str)
df_spazio['LATITUDE'] = df_spazio.apply(lambda x: converter(x['LATITUDE']), axis =1 )
df_spazio['LATITUDE'] = df_spazio['LATITUDE'].astype(float)

df_spazio['LONGITUDE'] = df_spazio['LONGITUDE'].astype(str)
df_spazio['LONGITUDE'] = df_spazio.apply(lambda x: converter(x['LONGITUDE']), axis =1 )
df_spazio['LONGITUDE'] = df_spazio['LONGITUDE'].astype(float)

In [137]:
df_solucoes5.head()

       END_ID    ENodeB
0  RNCIC_0002  NLKCKC00
1  RNCIC_0005  NLKCKC03
2  RNCIC_0007  NLKCKC06

In [138]:
#df_solucoes1 = df_solucoes1.merge(df_spazio, left_on = 'ENDEREÇO ID', right_on='Endereço ID', how='left')
#df_solucoes2 = df_solucoes2.merge(df_spazio, left_on = 'ENDEREÇO ID', right_on='Endereço ID', how='left')
#df_solucoes3 = df_solucoes3.merge(df_spazio, left_on = 'END_ID', right_on='Endereço ID', how='left')
#df_solucoes4 = df_solucoes4.merge(df_spazio, left_on = 'END_ID', right_on='Endereço ID', how='left')
df_solucoes5 = df_solucoes5.merge(df_spazio, left_on = 'END_ID', right_on='Endereço ID', how='left')

df_cel_Criticas = df_cel_Criticas.merge(df_spazio, left_on = 'END_ID', right_on='Endereço ID', how='left')
df_NT4G  = df_NT4G.merge(df_spazio, left_on = 'EndId', right_on='Endereço ID', how='left')
#df_cel_Criticas.drop(['Latitude', 'Longitude'], axis=1, inplace = True)
#df_solucoes5.drop(['Latitude', 'Longitude'], axis=1, inplace = True)

In [139]:
df_cel_Criticas.head()

,Fornecedor,END_ID,ENodeB,Célula,Município,IBGE,Estado,ANF,Faixa Populacional,Regional,Banda,Operadora,DISTÂNCIA,AZIMUTE,SOLUÇÃO\nPMO_ROLLOUT,SOLUÇÃO\nPMO_SUSPENDED,SOLUÇÃO\nFORA PLANO,Endereço ID,LATITUDE,LONGITUDE
0,NaN,RNCIC_0002,NLKCKC00,NLKCKC00K,Caico,NaN,RN,NaN,NaN,NaN,1800,NaN,900,290,NaN,NaN,NaN,RNCIC_0002,-6.4678,-37.086953
1,NaN,RNCIC_0002,NLKCKC00,NLKCKC00K,Caico,NaN,RN,NaN,NaN,NaN,1800,NaN,900,290,NaN,NaN,NaN,RNCIC_0002,-6.4678,-37.086953
2,NaN,RNCIC_0002,NLKCKC00,NLKCKC00K,Caico,NaN,RN,NaN,NaN,NaN,1800,NaN,900,290,NaN,NaN,NaN,RNCIC_0002,-6.4678,-37.086953
3,NaN,RNCIC_0002,NLKCKC00,NLKCKC00K,Caico,NaN,RN,NaN,NaN,NaN,1800,NaN,900,290,NaN,NaN,NaN,RNCIC_0002,-6.4678,-37.086953
4,NaN,RNCIC_0002,NLKCKC00,NLKCKC00K,Caico,NaN,RN,NaN,NaN,NaN,1800,NaN,900,290,NaN,NaN,NaN,RNCIC_0002,-6.4678,-37.086953

In [140]:
df_cel_Criticas=df_cel_Criticas[['ENodeB','Célula','AZIMUTE','DISTÂNCIA','LATITUDE','LONGITUDE']]
df_cel_Criticas.rename(columns={"LATITUDE": "LAT", "LONGITUDE": "LONG"}, inplace = True)

#df_solucoes1=df_solucoes1[['CHAVE NETFLOW','LATITUDE','LONGITUDE']]
#df_solucoes2=df_solucoes2[['ORDEM COMPLEXA','LATITUDE','LONGITUDE']]
#df_solucoes3=df_solucoes3[['CHAVE','LATITUDE','LONGITUDE']]
#df_solucoes4=df_solucoes4[['CHAVE','LATITUDE','LONGITUDE']]
#df_solucoes5=df_solucoes5[['EndId','LATITUDE','LONGITUDE']]
#df_solucoes1.rename(columns={"LAT": "LATITUDE", "LONG": "LONGITUDE"}, inplace = True)
#df_solucoes2.rename(columns={"LAT": "LATITUDE", "LONG": "LONGITUDE"}, inplace = True)
#df_solucoes3.rename(columns={"LAT": "LATITUDE", "LONG": "LONGITUDE"}, inplace = True)

In [141]:
df_cel_Criticas.shape
# Apos o merge, repetiu-se varias células na df_cel_Criticas (depois ver porque isso ocorreu). Por hora, só deletei as celulas repetidas
# Nesse assessement de fevereiro, tem 1287 (rev2)

(27, 6)

In [142]:
df_cel_Criticas.drop_duplicates(inplace=True)
df_NT4G.drop_duplicates(inplace=True)
df_solucoes5.drop_duplicates(inplace=True)
total_cel_criticas = df_cel_Criticas.shape[0]

In [143]:
df_cel_Criticas.head()

      ENodeB     Célula  AZIMUTE  DISTÂNCIA       LAT       LONG
0   NLKCKC00  NLKCKC00K      290        900 -6.467800 -37.086953
5   NLKCKC03  NLKCKC03I       60        900 -6.473894 -37.095558
9   NLKCKC04  NLKCKC04G      230       1500 -6.467861 -37.107694
11  NLKCKC04  NLKCKC04I       30        900 -6.467861 -37.107694
13  NLKCKC04  NLKCKC04J      170        900 -6.467861 -37.107694

In [144]:
df_NT4G.head()

,EndId,ENodeB,Célula,Município,Estado,Banda,AZIMUTE,Endereço ID,LATITUDE,LONGITUDE
0,RNCIC_0002,NLKCKC00,NLKCKC00F,Caico,RN,700,120,RNCIC_0002,-6.4678,-37.086953
5,RNCIC_0002,NLKCKC00,NLKCKC00R,Caico,RN,2100,120,RNCIC_0002,-6.4678,-37.086953
10,RNCIC_0002,NLKCKC00,NLKCKC00S,Caico,RN,2100,290,RNCIC_0002,-6.4678,-37.086953
15,RNCIC_0002,NLKCKC00,NLKCKC00Q,Caico,RN,2100,0,RNCIC_0002,-6.4678,-37.086953
20,RNCIC_0002,NLKCKC00,NLKCKC00G,Caico,RN,700,290,RNCIC_0002,-6.4678,-37.086953

#df_cel_Criticas['LAT'] = df_cel_Criticas['LAT'].apply(lambda X: float(X.replace(".","").replace(",",".")))


### Se a distancia for zero => Ignora o Azimute

### Verificar o Math de azimute:

### O candidato será valido se a distancia < MAX_DIST e o |Az calculado do site solucao - Az Setor critico | < = 35°

### depois podemos criar um Score que leve em conta as duas variaveis (distancia e |delta azimute|) para rankear. 
### Tipo: quem é melhor: 1- site a 1,5Km e delta azimute = 0 ou site a 1km e delta azimute = 35 ? 

### Inicialmente será: Menor distancia e passar no crivo do azimute

In [145]:
#dado Lat1, Long1 e Lat2, Long2. Calcula a distancia(s12) e azimute (azi1), sentido ponto1 para ponto2
# dado dois pontos, calcula a distancia, azimute de saida e chegada. pra pequenas distancias, azi1 = azi2
d= geod.Inverse(0.1, 0.00, 0,0)

In [146]:
d

{'lat1': 0.1,
 'lon1': 0.0,
 'lat2': 0,
 'lon2': 0,
 'a12': 0.0996647196109874,
 's12': 11057.427694902271,
 'azi1': 180.0,
 'azi2': 180.0}

In [150]:
def find_best_match(df_solucoes,                 # Dataframe com o universo de sites para serem verificados como solução ao setor critico. 
                    CHAVE,                       # Nome da coluna df_solucoes com a chave que será retornada. Pode ser o nome do site, END_ID, OC, etc
                    coluna_lat_solucoes,         # Nome da coluna do DF com as Latitudes dos sites a serem testados
                    coluna_lon_solucoes,         # Nome da coluna do DF com as Longitudes dos sites a serem testados
                    Lat_critico,                 # Latitude do site critico
                    Lon_critico,                 # Longitude do site critico
                    AZIMUTE_SETOR_CRITICO,       # Azimute do setor critico
                    MAX_DIST,                    # Se não informar o valor, assume 2km como padrão             
                    df_NT,                        ## NexTim com as Informacoes de coordenadas e azimutes das células da rede
                    contador_recursivo           #
                    ):                              
    """
    Encontrar o melhor site para resolver o problema do site critico
    Dado LAT, LONG, AZIMUTE E MAX_DIST, encontra o site em plano mais proximo e mais centralizado no azimute informado.
    so considera candidatos com distancia inferior a MAX_DIST
    df_solucoes - DataFrame com as solucoes
    Chave: Qual a coluna com a Chave para interar na Planilha. Pode ser ORDEM_Complexa ou outra.
    
    """
    if MAX_DIST < 1000:
        erro = 0.02 #Distancia calculada de 2211m
    elif MAX_DIST >=1000 or MAX_DIST <2000:
        erro = 0.04
    else:
        erro =0.1


    menor_dist = 9999999
    azimute_solucao = 0
    site = ''
    for index, row in df_solucoes.iterrows():
        #print("--- %.2f %% Concluido ---" % ((index / total_cel_criticas)*100))
        # O calculo de distancia e azimute completo é computacionalmente dispendioso, por isso realizo um crivo antes para evitar realizar calculos em sites que são muito distantes entre si.
        # Como testado na celula acima, uma diferenca de 0.1 em latitude ou longitude implica em uma distancia superior a 10km. Por isso, ja testo logo. Se o site a ser verificado tem um deltaLat ou
        # deltaLong superior a 0.1, nem calculo. Passa para o proximo site.
         
        if abs(abs(Lat_critico) - abs(row[coluna_lat_solucoes])) > erro or abs(abs(Lon_critico) - abs(row[coluna_lon_solucoes])) > erro:
            pass
        else:
            calculo =  geod.Inverse(Lat_critico,Lon_critico,row[coluna_lat_solucoes],row[coluna_lon_solucoes])
            distancia = calculo['s12']
            azimute_calculado = calculo['azi1']

            if azimute_calculado < 0:
                azimute_calculado += 360 # Corrige a diferença de azimutes. a API fornece em + e - 180. preciso entre 0 e 360
        
            #check1: VErificar se o site esta no azimute do setor Critico + ou - 32°
            if abs( abs(AZIMUTE_SETOR_CRITICO) - abs(azimute_calculado)) <= 32:
                if distancia < menor_dist:
                    site = row[CHAVE]
                    lat_solucao = row[coluna_lat_solucoes] ## latitude e longitude do site solucao encontrado
                    lon_solucao = row[coluna_lon_solucoes]
                    menor_dist = distancia
                    azimute_solucao = azimute_calculado
            if menor_dist == 0:
                #print('distancia =0')
                return site

    if contador_recursivo == 2:
        #print(site, lat_solucao, lon_solucao,AZIMUTE_SETOR_CRITICO+180,MAX_DIST)
        df_NT = df_NT.loc[df_NT['LATITUDE']==Lat_critico] # filtrando apenas o site solucao para ser verificado 
        #print(df_NT)
        find_best_match(df_NT,'Célula','LATITUDE','LONGITUDE',lat_solucao,lon_solucao,AZIMUTE_SETOR_CRITICO+180,MAX_DIST,df_NT,1)
    else:
        if menor_dist <= MAX_DIST:
            #print(index)
            print(site)
            return site #[site , menor_dist, azimute_solucao]
        
        elif menor_dist == 0:
            #print(site,0,0)
            return site # [site , 0, 0]

        else:
            print('sem solucao')
            return np.nan

In [151]:
#df_NT4G.loc[df_NT4G['ENodeB']=='NLKCKC06']
#df_NT4G.loc[df_NT4G['ENodeB']==-6.]

In [152]:
saida = find_best_match(df_solucoes5,'ENodeB','LATITUDE','LONGITUDE',-6.460000,-37.10000,30,8000,df_NT4G,2)

NLKCKC01E

In [132]:
df_NT4G.loc[df_NT4G['LATITUDE']==-6.46]

,EndId,ENodeB,Célula,Município,Estado,Banda,AZIMUTE,Endereço ID,LATITUDE,LONGITUDE
50,RNCIC_0001,NLKCKC01,NLKCKC01E,Caico,RN,700,30,RNCIC_0001,-6.46,-37.1
61,RNCIC_0001,NLKCKC01,NLKCKC01F,Caico,RN,700,150,RNCIC_0001,-6.46,-37.1
72,RNCIC_0001,NLKCKC01,NLKCKC01G,Caico,RN,700,270,RNCIC_0001,-6.46,-37.1
83,RNCIC_0001,NLKCKC01,NLKCKC01I,Caico,RN,1800,30,RNCIC_0001,-6.46,-37.1
94,RNCIC_0001,NLKCKC01,NLKCKC01J,Caico,RN,1800,150,RNCIC_0001,-6.46,-37.1
105,RNCIC_0001,NLKCKC01,NLKCKC01K,Caico,RN,1800,270,RNCIC_0001,-6.46,-37.1

In [15]:
#find_best_match(-8.126917,-34.905056,180,900) TESTE
find_best_match(df_solucoes1,'CHAVE NETFLOW',-8.119672,-34.903547,0,1900)
#find_best_match(df_solucoes2,'ORDEM COMPLEXA',-8.119672,-34.903547,0,1900)
#find_best_match(df_solucoes3,'CHAVE',-8.119672,-34.903547,0,1900)

['SLRCBG092600PLAYER', 0, 0]

In [16]:

### CALCULO 
start_time = time.time()

#for index1, row1 in df_cel_Criticas.iterrows():
#    row1['Teste'] = find_best_mat+++ch(row1['LAT'], row1['LONG'], row1['azimute'], row1['DISTÂNCIA'])
#    print("--- %.2f %% Concluido ---\r" % ((index1 / total_cel_criticas)))

df_cel_Criticas['Solução1'] = df_cel_Criticas.apply(lambda x: find_best_match(df_solucoes1,'CHAVE NETFLOW', x['LAT'], x['LONG'], x['AZIMUTE'], x['DISTÂNCIA']),axis=1)
#df_cel_Criticas['Solução2'] = df_cel_Criticas.apply(lambda x: find_best_match(df_solucoes2,'ORDEM COMPLEXA', x['LAT'], x['LONG'], x['AZIMUTE'], x['DISTÂNCIA']),axis=1)
#df_cel_Criticas['Solução3'] = df_cel_Criticas.apply(lambda x: find_best_match(df_solucoes3,'CHAVE', x['LAT'], x['LONG'], x['AZIMUTE'], x['DISTÂNCIA']),axis=1)
#df_cel_Criticas['Solução4'] = df_cel_Criticas.apply(lambda x: find_best_match(df_solucoes4,'CHAVE', x['LAT'], x['LONG'], x['AZIMUTE'], x['DISTÂNCIA']),axis=1)


df_cel_Criticas.to_excel('Solucao_fev_rev3.xlsx')

tempo_total = time.time() - start_time
print('Tempo Total(em horas):', tempo_total / 3600)

Tempo Total(em horas): 0.20149113794167836

In [145]:
tempo_total

2097.9712488651276